apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: flight-app
type: Opaque
data:
  # echo -n 'postgres://postgres:password@user-db:5432/userdb' | base64
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEB1c2VyLWRiOjU0MzIvdXNlcmRi
  # echo -n 'change-me-in-production' | base64
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
