apiVersion: v1
kind: Secret
metadata:
  name: booking-service-secret
  namespace: flight-app
type: Opaque
data:
  # echo -n 'postgres://postgres:password@booking-db:5432/bookingdb' | base64
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBib29raW5nLWRiOjU0MzIvYm9va2luZ2Ri
  # echo -n 'change-me-in-production' | base64
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
