apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-db
  namespace: flight-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight-db
  template:
    metadata:
      labels:
        app: flight-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: flightdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: flight-db-storage
              mountPath: /var/lib/postgresql/data
            - name: flight-db-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: flight-db-storage
          persistentVolumeClaim:
            claimName: flight-db-pvc
        - name: flight-db-init
          configMap:
            name: flight-db-init
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flight-db-pvc
  namespace: flight-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
