apiVersion: v1
kind: Secret
metadata:
  name: flight-service-secret
  namespace: flight-app
type: Opaque
data:
  # echo -n 'postgres://postgres:password@flight-db:5432/flightdb' | base64
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBmbGlnaHQtZGI6NTQzMi9mbGlnaHRkYg==
