apiVersion: v1
kind: Service
metadata:
  name: flight-service
  namespace: flight-app
spec:
  selector:
    app: flight-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
